server:
  port: 8080

spring:
  datasource:
    #druid:
      url: jdbc:mysql://127.0.0.1:3306/bbs?serverTimezone=UTC
      username: root
      password: root
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false
    #mode: LEGACYHTML5
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0

      host: 127.0.0.1
      port: 6379
      password:
      database: 0

mybatis:
  type-aliases-package: com.yusys.bbs.entity
  mapper-locations: classpath:mapper/*.xml
